"""Subhalo boost helper functions for s-wave annihilation precompute tables.

This module is centered on the new SASHIMI-C HDF5 boost table generated by

    build_sashimi_boost_table_continuous_margin.ipynb

The production table stores the total luminosity multiplier

    boost_total = L_total / L_host,0 = 1 - f_sh**2 + B_sh

on a regular grid in (z, m_host).  The table is intended to be used
multiplicatively on the host-only s-wave annihilation rate.

Conservative convention:
    - Interpolate directly in B, not log(B), matching the notebook.
    - Interpolate in (z, log(m_host)).
    - Outside the table, or for non-positive/invalid host masses, return 1.
    - Final returned values are clipped to be >= 1 by default.

The old analytic/Hiroshima-style functions are kept at the bottom for
backward compatibility, but the recommended production path is the SASHIMI
HDF5 table loader.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Callable, Dict, Mapping, Optional, Tuple

import h5py
import numpy as np
from scipy.integrate import quad
from scipy.interpolate import RegularGridInterpolator


# =============================================================================
# New production path: SASHIMI-C HDF5 boost table
# =============================================================================

DEFAULT_SASHIMI_TAG = "continuousMargin_Nz231_Nm211_Zmax46"
DEFAULT_SASHIMI_BOOST_FILENAME = (
    f"subhalo_boost_sashimi_final_{DEFAULT_SASHIMI_TAG}.h5"
)


def default_sashimi_boost_path(
    data_dir: Optional[str | os.PathLike[str]] = None,
    filename: str = DEFAULT_SASHIMI_BOOST_FILENAME,
) -> Path:
    """Return the default path to the SASHIMI-C production boost table.

    The notebook saves the table directly under ``DM21CM_DATA_DIR``:

        $DM21CM_DATA_DIR/subhalo_boost_sashimi_final_continuousMargin_Nz231_Nm211_Zmax46.h5

    Parameters
    ----------
    data_dir:
        Optional base data directory. If omitted, read from the environment
        variable ``DM21CM_DATA_DIR``. If the environment variable is also
        missing, use the same fallback as the notebook.
    filename:
        HDF5 filename.

    Returns
    -------
    pathlib.Path
        Candidate table path.
    """
    if data_dir is None:
        data_dir = os.environ.get(
            "DM21CM_DATA_DIR",
            "/work/src/dm21cm_stack/data/DM21cm_data",
        )
    return Path(data_dir) / filename


def _decode_attr(value: Any) -> Any:
    """Make HDF5 attributes friendlier for metadata dictionaries."""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    if isinstance(value, np.generic):
        return value.item()
    return value


def _read_optional_dataset(f: h5py.File, name: str) -> Optional[np.ndarray]:
    return f[name][:] if name in f else None


def load_sashimi_boost_table(
    filename: Optional[str | os.PathLike[str]] = None,
    *,
    boost_key: str = "boost_total",
    z_key: str = "z",
    mass_key: str = "m_host",
    read_diagnostic_masks: bool = True,
) -> Dict[str, Any]:
    """Load a SASHIMI-C subhalo boost table from HDF5.

    Parameters
    ----------
    filename:
        Path to the HDF5 table. If omitted, use :func:`default_sashimi_boost_path`.
    boost_key:
        Dataset containing the production multiplier. Default: ``boost_total``.
    z_key:
        Redshift grid dataset. Default: ``z``.
    mass_key:
        Host mass grid dataset in solar masses. Default: ``m_host``.
    read_diagnostic_masks:
        If True, also read available masks such as ``valid_clean``,
        ``interp_mask`` and ``fallback_mask`` into the output dictionary.

    Returns
    -------
    dict
        A dictionary with at least ``z``, ``m_host``, ``boost_total``,
        ``attrs`` and ``filename``.
    """
    path = Path(filename) if filename is not None else default_sashimi_boost_path()
    if not path.exists():
        raise FileNotFoundError(
            f"SASHIMI boost table not found: {path}\n"
            "Either generate it with build_sashimi_boost_table_continuous_margin.ipynb "
            "or pass the correct filename explicitly."
        )

    with h5py.File(path, "r") as f:
        missing = [key for key in (z_key, mass_key, boost_key) if key not in f]
        if missing:
            raise KeyError(
                f"Missing dataset(s) {missing} in {path}. "
                f"Available datasets: {list(f.keys())}"
            )

        z = np.asarray(f[z_key][:], dtype=float)
        m_host = np.asarray(f[mass_key][:], dtype=float)
        boost = np.asarray(f[boost_key][:], dtype=float)

        data: Dict[str, Any] = {
            "filename": str(path),
            "z": z,
            "m_host": m_host,
            "boost_total": boost,
            "attrs": {k: _decode_attr(v) for k, v in f.attrs.items()},
        }

        if read_diagnostic_masks:
            for name in (
                "boost_raw",
                "Bsh_raw",
                "fsh_raw",
                "n_sub_eff_raw",
                "valid_raw",
                "valid_clean",
                "outlier_mask",
                "inside_domain_mask",
                "inside_domain_padded_mask",
                "boundary_pad_mask",
                "interp_mask",
                "fallback_mask",
                "below_clip_mask",
                "failure_code",
                "min_valid_mass",
                "max_valid_mass",
                "zmax",
                "zmax_margin",
            ):
                arr = _read_optional_dataset(f, name)
                if arr is not None:
                    data[name] = arr

    _validate_sashimi_boost_arrays(z, m_host, boost, path)
    return data


def _validate_sashimi_boost_arrays(
    z: np.ndarray,
    m_host: np.ndarray,
    boost: np.ndarray,
    filename: str | os.PathLike[str],
) -> None:
    """Validate the minimal table structure before building an interpolator."""
    if z.ndim != 1:
        raise ValueError(f"{filename}: z must be one-dimensional, got shape {z.shape}.")
    if m_host.ndim != 1:
        raise ValueError(
            f"{filename}: m_host must be one-dimensional, got shape {m_host.shape}."
        )
    if boost.shape != (len(z), len(m_host)):
        raise ValueError(
            f"{filename}: boost table shape must be (len(z), len(m_host)) = "
            f"{(len(z), len(m_host))}, got {boost.shape}."
        )
    if len(z) < 2 or len(m_host) < 2:
        raise ValueError(f"{filename}: z and m_host grids must have at least 2 points.")
    if not np.all(np.diff(z) > 0):
        raise ValueError(f"{filename}: z grid must be strictly increasing.")
    if not np.all(np.diff(m_host) > 0):
        raise ValueError(f"{filename}: m_host grid must be strictly increasing.")
    if not np.all(m_host > 0):
        raise ValueError(f"{filename}: all host masses must be positive.")
    if not np.all(np.isfinite(boost)):
        raise ValueError(f"{filename}: boost table contains non-finite values.")


def build_sashimi_boost_interpolator(
    filename: Optional[str | os.PathLike[str]] = None,
    *,
    boost_key: str = "boost_total",
    fallback_to_unity: bool = True,
    clip_min_boost: float = 1.0,
    read_diagnostic_masks: bool = True,
) -> Tuple[Callable[[Any, Any], np.ndarray | float], Dict[str, Any]]:
    """Build a callable boost interpolator from the SASHIMI-C HDF5 table.

    The callable has signature

        boost(Mhost, z)

    and supports scalar or array inputs with NumPy broadcasting.

    Parameters
    ----------
    filename:
        Path to the SASHIMI HDF5 table. If omitted, use the default path.
    boost_key:
        Dataset to interpolate. Production use should keep ``boost_total``.
    fallback_to_unity:
        If True, outside-table points return 1. If False, scipy extrapolates
        linearly outside the table because ``fill_value=None``.
    clip_min_boost:
        Minimum returned boost. Use 1.0 for the conservative production
        convention. Set to ``None`` to disable clipping.
    read_diagnostic_masks:
        Include optional diagnostic arrays in the returned metadata.

    Returns
    -------
    interpolator, metadata
        ``interpolator(Mhost, z)`` returns the boost multiplier.
        ``metadata`` contains the loaded table and useful attributes.
    """
    table = load_sashimi_boost_table(
        filename,
        boost_key=boost_key,
        read_diagnostic_masks=read_diagnostic_masks,
    )
    z_grid = table["z"]
    m_grid = table["m_host"]
    boost_table = table["boost_total"]

    fill_value = 1.0 if fallback_to_unity else None
    rgi = RegularGridInterpolator(
        (z_grid, np.log(m_grid)),
        boost_table,
        bounds_error=False,
        fill_value=fill_value,
    )

    log_m_min = float(np.log(m_grid[0]))
    log_m_max = float(np.log(m_grid[-1]))
    z_min = float(z_grid[0])
    z_max = float(z_grid[-1])

    def interpolator(Mhost: Any, z: Any) -> np.ndarray | float:
        M_arr = np.asarray(Mhost, dtype=float)
        z_arr = np.asarray(z, dtype=float)
        z_b, M_b = np.broadcast_arrays(z_arr, M_arr)

        out = np.ones(z_b.shape, dtype=float)

        good_mass = np.isfinite(M_b) & (M_b > 0)
        good_z = np.isfinite(z_b)
        good = good_mass & good_z

        if np.any(good):
            pts = np.column_stack(
                [
                    z_b[good].ravel(),
                    np.log(M_b[good]).ravel(),
                ]
            )
            vals = np.asarray(rgi(pts), dtype=float)

            # If fallback_to_unity=False, extrapolation may still produce
            # non-finite or sub-unity values; handle these conservatively.
            vals = np.where(np.isfinite(vals), vals, 1.0)
            if clip_min_boost is not None:
                vals = np.maximum(vals, float(clip_min_boost))

            out[good] = vals.reshape(-1)

        if out.shape == ():
            return float(out)
        return out

    metadata: Dict[str, Any] = dict(table)
    metadata.update(
        {
            "table": boost_table,  # backward-compatible alias
            "M_grid": m_grid,
            "z_grid": z_grid,
            "boost_key": boost_key,
            "fallback_to_unity": bool(fallback_to_unity),
            "clip_min_boost": clip_min_boost,
            "interpolation_space": "(z, log(m_host))",
            "interpolation_quantity": "B, not logB",
            "z_min": z_min,
            "z_max": z_max,
            "m_host_min": float(m_grid[0]),
            "m_host_max": float(m_grid[-1]),
            "log_m_host_min": log_m_min,
            "log_m_host_max": log_m_max,
        }
    )
    return interpolator, metadata


def load_sashimi_boost_interpolator(
    filename: Optional[str | os.PathLike[str]] = None,
    **kwargs: Any,
) -> Callable[[Any, Any], np.ndarray | float]:
    """Convenience wrapper returning only the SASHIMI boost interpolator."""
    interpolator, _metadata = build_sashimi_boost_interpolator(filename, **kwargs)
    return interpolator


def sashimi_total_boost(
    Mhost: Any,
    z: Any,
    filename: Optional[str | os.PathLike[str]] = None,
    **kwargs: Any,
) -> np.ndarray | float:
    """Evaluate the SASHIMI table boost directly.

    This is convenient for one-off checks. For loops, build the interpolator once
    with :func:`build_sashimi_boost_interpolator` and reuse it.
    """
    interp = load_sashimi_boost_interpolator(filename, **kwargs)
    return interp(Mhost, z)


def describe_sashimi_table(metadata: Mapping[str, Any]) -> str:
    """Return a compact human-readable summary of a loaded SASHIMI table."""
    filename = metadata.get("filename", "<unknown>")
    z_min = metadata.get("z_min", np.nan)
    z_max = metadata.get("z_max", np.nan)
    m_min = metadata.get("m_host_min", np.nan)
    m_max = metadata.get("m_host_max", np.nan)
    table = metadata.get("boost_total", metadata.get("table", None))
    if table is None:
        b_min = b_max = np.nan
    else:
        b_min = float(np.nanmin(table))
        b_max = float(np.nanmax(table))
    return (
        f"SASHIMI-C HDF5 boost table: {filename}; "
        f"z=[{z_min:.6g}, {z_max:.6g}], "
        f"Mhost=[{m_min:.6e}, {m_max:.6e}] Msun, "
        f"Btot=[{b_min:.6g}, {b_max:.6g}], "
        f"fallback_to_unity={metadata.get('fallback_to_unity', None)}, "
        f"clip_min_boost={metadata.get('clip_min_boost', None)}"
    )


# =============================================================================
# Compatibility API expected by older build_swave_tables.py
# =============================================================================

def build_total_boost_interpolator(
    model: str = "sashimi",
    *,
    table_path: Optional[str | os.PathLike[str]] = None,
    filename: Optional[str | os.PathLike[str]] = None,
    fallback_to_unity: bool = True,
    clip_min_boost: float = 1.0,
    **legacy_kwargs: Any,
) -> Tuple[Callable[[Any, Any], np.ndarray | float], Dict[str, Any]]:
    """Build a total-boost interpolator.

    Recommended use:
        build_total_boost_interpolator(model="sashimi", table_path="...h5")

    For backward compatibility, ``model='correa'`` or ``model='okoli'`` still
    constructs the old analytic interpolator using the legacy keyword arguments.
    """
    model_lower = str(model).lower()

    if model_lower in ("sashimi", "sashimi_h5", "h5", "table"):
        path = table_path if table_path is not None else filename
        return build_sashimi_boost_interpolator(
            path,
            fallback_to_unity=fallback_to_unity,
            clip_min_boost=clip_min_boost,
        )

    if model_lower in ("correa", "okoli"):
        return build_analytic_total_boost_interpolator(
            model=model_lower,
            fallback_to_unity=fallback_to_unity,
            **legacy_kwargs,
        )

    raise ValueError(
        "Unknown subhalo boost model. Use 'sashimi' for the HDF5 table, "
        "or 'correa'/'okoli' for the legacy analytic prescription."
    )


def describe_model_configuration(
    model: str = "sashimi",
    *,
    table_path: Optional[str | os.PathLike[str]] = None,
    filename: Optional[str | os.PathLike[str]] = None,
    **kwargs: Any,
) -> str:
    """Human-readable model summary string."""
    model_lower = str(model).lower()
    if model_lower in ("sashimi", "sashimi_h5", "h5", "table"):
        path = table_path if table_path is not None else filename
        if path is None:
            path = default_sashimi_boost_path()
        return (
            f"model=sashimi_h5, table_path={path}, "
            f"fallback_to_unity={kwargs.get('fallback_to_unity', True)}, "
            f"clip_min_boost={kwargs.get('clip_min_boost', 1.0)}"
        )

    return (
        f"model={model}, m_min={kwargs.get('m_min', 1e-6):.6e}, "
        f"fsh_mmax_mode={kwargs.get('fsh_mmax_mode', 'mc')}, "
        f"host_m_min={kwargs.get('host_m_min', None)}, "
        f"host_m_max={kwargs.get('host_m_max', None)}, "
        f"z_max={kwargs.get('z_max', 6.0)}"
    )


# =============================================================================
# Legacy analytic prescription, retained for comparison only
# =============================================================================

# ----- Subhalo mass function: m^2 dN/dm = (a + b m^alpha) exp[-(m/mc)^beta]

def a_sub(Mhost: float, z: float) -> float:
    logM = np.log10(Mhost)
    return (
        6.0e-4
        * Mhost
        * (2 - 0.08 * logM) ** 2
        * (np.log10(Mhost / 1e-5)) ** (-0.1)
        * (1 + z)
    )


def b_sub(Mhost: float, z: float) -> float:
    logM = np.log10(Mhost)
    return (
        8.0e-5
        * Mhost
        * (2 - 0.08 * logM)
        * (np.log10(Mhost / 1e-5)) ** (-0.08 * z)
        * (np.log10(Mhost / 1e-8)) ** (-1)
        * (np.log10(Mhost / 1e18)) ** 2
    )


def mc_sub(Mhost: float, z: float) -> float:
    return 0.05 * (1 + z) * Mhost


def alpha_sub(z: float) -> float:
    return 0.2 + 0.02 * z


def beta_sub() -> float:
    return 3.0


def m2_dNdm_sub(m: float, Mhost: float, z: float) -> float:
    aa = a_sub(Mhost, z)
    bb = b_sub(Mhost, z)
    al = alpha_sub(z)
    be = beta_sub()
    mc = mc_sub(Mhost, z)
    return (aa + bb * m ** al) * np.exp(-(m / mc) ** be)


def dNdm_sub(m: float, Mhost: float, z: float) -> float:
    return m2_dNdm_sub(m, Mhost, z) / (m ** 2)


def get_fsh_mmax(Mhost: float, z: float, mode: str = "mc") -> float:
    """Upper integration limit for the legacy f_sh calculation."""
    if mode == "mc":
        return mc_sub(Mhost, z)
    if mode == "0.1M":
        return 0.1 * Mhost
    if mode == "M":
        return Mhost
    raise ValueError("mode must be 'mc', '0.1M', or 'M'.")


def f_sh(
    Mhost: float,
    z: float,
    m_min: float = 1e-6,
    m_max: Optional[float] = None,
    epsrel: float = 1e-6,
    mmax_mode: str = "mc",
) -> float:
    """Legacy subhalo mass fraction."""
    if Mhost <= 0:
        raise ValueError("Mhost must be positive.")
    if m_max is None:
        m_max = get_fsh_mmax(Mhost, z, mode=mmax_mode)
    if m_min <= 0 or m_max <= m_min:
        raise ValueError("Need m_max > m_min > 0.")

    def integrand_ln_m(lnm: float) -> float:
        m = np.exp(lnm)
        return (m * dNdm_sub(m, Mhost, z)) * m

    val, _err = quad(
        integrand_ln_m,
        np.log(m_min),
        np.log(m_max),
        epsrel=epsrel,
        limit=500,
    )
    return float(val / Mhost)


# ----- Legacy B_sh fitting functions

def X_correa(z: float) -> float: return 2.7 * np.exp(-0.2 * z) + 0.15
def Y_correa(z: float) -> float: return 0.4 + (-0.224 * z + 0.56) * np.exp(-0.8 * z)
def a_correa(z: float) -> float: return 0.10 + 0.095 * np.exp(-0.5 * z)
def b_correa(z: float) -> float: return 0.03 * z ** 2 - 0.08 * z - 0.83
def c_correa(z: float) -> float: return 0.004 * z ** 2 - 0.04 * z - 0.6
def m1_correa(z: float) -> float: return -3.17 * z + 17.4
def m2_correa(z: float) -> float: return -(0.2 * z - 1.0) ** 5 - 4.0

def X_okoli(z: float) -> float: return 2.2 * np.exp(-0.75 * z) + 0.67
def Y_okoli(z: float) -> float: return 2.5 * np.exp(-0.005 * z) + 0.8
def a_okoli(z: float) -> float: return 0.1 * np.exp(-0.5 * z) + 0.22
def b_okoli(z: float) -> float: return 0.8 * np.exp(-0.5 * (z - 12.0) ** 4) - 0.24
def c_okoli(z: float) -> float: return -0.0005 * z ** 3 - 0.032 * z ** 2 + 0.28 * z - 1.12
def m1_okoli(z: float) -> float: return -2.6 * z + 8.2
def m2_okoli(z: float) -> float: return 0.1 * np.exp(-3.0 * z) - 12.0


def log10_Bsh(Mhost: float, z: float, model: str = "correa") -> float:
    """Legacy log10 of the subhalo annihilation boost B_sh."""
    if Mhost <= 0:
        raise ValueError("Mhost must be positive.")
    logM = np.log10(Mhost)

    if model.lower() == "correa":
        X, Y = X_correa(z), Y_correa(z)
        aa, bb, cc = a_correa(z), b_correa(z), c_correa(z)
        m1, m2 = m1_correa(z), m2_correa(z)
    elif model.lower() == "okoli":
        X, Y = X_okoli(z), Y_okoli(z)
        aa, bb, cc = a_okoli(z), b_okoli(z), c_okoli(z)
        m1, m2 = m1_okoli(z), m2_okoli(z)
    else:
        raise ValueError("model must be 'correa' or 'okoli'.")

    term1 = X / (1.0 + np.exp(-aa * (logM - m1)))
    term2 = cc * (1.0 + Y / (1.0 + np.exp(-bb * (logM - m2))))
    return float(term1 + term2)


def B_sh(Mhost: float, z: float, model: str = "correa") -> float:
    return float(10 ** log10_Bsh(Mhost, z, model=model))


def boost_is_applicable(
    Mhost: float,
    z: float,
    host_m_min: Optional[float] = None,
    host_m_max: Optional[float] = None,
    z_max: Optional[float] = 6.0,
) -> bool:
    """Applicability gate for the legacy analytic prescription."""
    if z_max is not None and z > z_max:
        return False
    if host_m_min is not None and Mhost < host_m_min:
        return False
    if host_m_max is not None and Mhost > host_m_max:
        return False
    return True


def total_boost(
    Mhost: float,
    z: float,
    model: str = "correa",
    m_min: float = 1e-6,
    fsh_mmax_mode: str = "mc",
    host_m_min: Optional[float] = None,
    host_m_max: Optional[float] = None,
    z_max: Optional[float] = 6.0,
    fallback_to_unity: bool = True,
    integration_epsrel: float = 1e-6,
) -> float:
    """Legacy total luminosity multiplier L_total / L_host,0."""
    if not boost_is_applicable(
        Mhost,
        z,
        host_m_min=host_m_min,
        host_m_max=host_m_max,
        z_max=z_max,
    ):
        if fallback_to_unity:
            return 1.0
        raise ValueError("Requested subhalo boost outside applicability range.")

    fsh = f_sh(
        Mhost,
        z,
        m_min=m_min,
        m_max=None,
        epsrel=integration_epsrel,
        mmax_mode=fsh_mmax_mode,
    )
    bsh = B_sh(Mhost, z, model=model)
    return float(max(1.0, 1.0 - fsh ** 2 + bsh))


def build_analytic_total_boost_interpolator(
    model: str = "correa",
    m_min: float = 1e-6,
    fsh_mmax_mode: str = "mc",
    host_m_min: float = 1e-4,
    host_m_max: float = 1e14,
    z_max: float = 6.0,
    fallback_to_unity: bool = True,
    integration_epsrel: float = 1e-6,
    z_grid: Optional[np.ndarray] = None,
    M_grid: Optional[np.ndarray] = None,
    **_unused: Any,
) -> Tuple[Callable[[Any, Any], np.ndarray | float], Dict[str, Any]]:
    """Build the old analytic boost interpolator.

    This function is retained only for comparison/reproducibility.
    Production s-wave tables should use the SASHIMI HDF5 table.
    """
    if z_grid is None:
        z_grid = np.linspace(0.0, z_max, 61)
    else:
        z_grid = np.asarray(z_grid, dtype=float)

    if M_grid is None:
        M_grid = np.geomspace(host_m_min, host_m_max, 161)
    else:
        M_grid = np.asarray(M_grid, dtype=float)

    table = np.zeros((len(z_grid), len(M_grid)), dtype=float)
    for i_z, zz in enumerate(z_grid):
        for i_m, mm in enumerate(M_grid):
            table[i_z, i_m] = total_boost(
                mm,
                zz,
                model=model,
                m_min=m_min,
                fsh_mmax_mode=fsh_mmax_mode,
                host_m_min=host_m_min,
                host_m_max=host_m_max,
                z_max=z_max,
                fallback_to_unity=fallback_to_unity,
                integration_epsrel=integration_epsrel,
            )

    rgi = RegularGridInterpolator(
        (z_grid, np.log(M_grid)),
        table,
        bounds_error=False,
        fill_value=1.0 if fallback_to_unity else None,
    )

    def interpolator(Mhost: Any, z: Any) -> np.ndarray | float:
        M_arr = np.asarray(Mhost, dtype=float)
        z_arr = np.asarray(z, dtype=float)
        z_b, M_b = np.broadcast_arrays(z_arr, M_arr)

        out = np.ones(z_b.shape, dtype=float)
        good = np.isfinite(z_b) & np.isfinite(M_b) & (M_b > 0)
        if np.any(good):
            pts = np.column_stack([z_b[good].ravel(), np.log(M_b[good]).ravel()])
            vals = np.asarray(rgi(pts), dtype=float)
            vals = np.where(np.isfinite(vals), vals, 1.0)
            vals = np.maximum(vals, 1.0)
            out[good] = vals.reshape(-1)

        if out.shape == ():
            return float(out)
        return out

    metadata = {
        "model": model,
        "z_grid": z_grid,
        "M_grid": M_grid,
        "table": table,
        "boost_total": table,
        "fallback_to_unity": fallback_to_unity,
        "legacy_analytic": True,
    }
    return interpolator, metadata
