"""Build s-wave annihilation HMF-summed precompute tables.

This is the SASHIMI-subhalo version of the s-wave table builder.

Main change relative to the old script
--------------------------------------
The old subhalo option used an analytic boost prescription that was normally
restricted to z <= 6.  This version reads the production SASHIMI-C HDF5 boost
interpolation table generated by

    build_sashimi_boost_table_continuous_margin.ipynb

and multiplies the host-only halo annihilation luminosity by

    Btot(M, z) = L_total / L_host,0.

The default boost table path is resolved inside subhalo_boost.py as

    $DM21CM_DATA_DIR/subhalo_boost_sashimi_final_continuousMargin_Nz231_Nm211_Zmax46.h5

Conservative convention inherited from subhalo_boost.py:
    - interpolate in (z, log Mhost), directly in Btot rather than log Btot;
    - outside the SASHIMI table, or for invalid masses/redshifts, return Btot=1;
    - clip final boosts to be >= 1.

The output table is intended to be selected in dm.py through

    modifier="subhalo_sashimi"

provided dm.py maps that modifier to

    swave_hmf_summed_rate_subhalo_sashimi.h5
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import astropy.units as u
import astropy.constants as c
from tqdm import tqdm

from dm21cm.utils import save_h5_dict, load_h5_dict
from dm21cm.precompute.halo import DM_FRAC, cmz, nfw_info
from dm21cm.precompute.subhalo_boost import (
    build_total_boost_interpolator,
    default_sashimi_boost_path,
    describe_model_configuration,
    describe_sashimi_table,
)


def partial_ann_rate_host(m, c_nfw, z):
    """Host-only partial annihilation rate dNpartial/dt [Msun^2 / pc^3].

    Definition
    ----------
    dNpartial/dt = 1/2 * DM_FRAC**2 * int dV rho_NFW^2.

    Therefore the full annihilation rate of a halo is

        dN/dt = sigma_v / m_DM^2 * dNpartial/dt.

    The subhalo boost table multiplies this host-only quantity by
    Btot(M, z) = L_total / L_host,0.
    """
    rho_s, r_s, r_delta = nfw_info(m, c_nfw, z)  # [Msun / pc^3], [pc], [pc]
    geom_factor = 1.0 - (1.0 + c_nfw) ** (-3)
    return 0.5 * DM_FRAC**2 * (64.0 * np.pi / 3.0) * rho_s**2 * r_s**3 * geom_factor


def _as_h5_string(value: object) -> np.bytes_:
    """Store metadata strings robustly with simple h5 helper functions."""
    return np.bytes_(str(value))


if __name__ == "__main__":

    # ======================================================================
    # Settings
    # ======================================================================

    # Halo masses above this value are excluded from the final HMF integral.
    # Keep inf unless you intentionally want a high-mass cutoff test.
    m_high_cutoff = np.inf  # [Msun]

    # This is the production filename used by dm.py with modifier="subhalo_sashimi".
    filename = "swave_hmf_summed_rate_subhalo_sashimi.h5"

    # Set False only for a host-only control table.  For the normal production
    # run of this file it should remain True.
    use_subhalo_boost = True
    subhalo_model = "sashimi"

    # If None, subhalo_boost.py uses the default path written in the notebook:
    # $DM21CM_DATA_DIR/subhalo_boost_sashimi_final_continuousMargin_Nz231_Nm211_Zmax46.h5
    subhalo_boost_table_path = None

    # Conservative interpolation policy for the SASHIMI HDF5 table.
    subhalo_fallback_to_unity = True
    subhalo_clip_min_boost = 1.0

    # Optional host-only output name if you temporarily set use_subhalo_boost=False.
    if not use_subhalo_boost:
        filename = "swave_hmf_summed_rate.h5"

    # ======================================================================
    # Initialization
    # ======================================================================

    data_dir = Path(os.environ["DM21CM_DATA_DIR"])
    save_dir = data_dir
    save_dir.mkdir(parents=True, exist_ok=True)

    hmfdata = load_h5_dict(str(data_dir / "precompute" / "hmf.h5"))
    z_s = np.asarray(hmfdata["z"], dtype=float)  # [1] redshift
    d_s = np.asarray(hmfdata["d"], dtype=float)  # [1] delta / overdensity
    m_s = np.asarray(hmfdata["m"], dtype=float)  # [Msun] halo mass

    # Extend z so that the final interpolated annihilation rate is explicitly
    # zero above the HMF table range.  This follows the old script logic.
    z_max = float(z_s[-1])
    zext_s = np.concatenate((z_s, [z_max + 1e-6, 4000.0]))

    boost_interp = None
    boost_interp_metadata = None

    if use_subhalo_boost:
        if subhalo_boost_table_path is None:
            subhalo_boost_table_path = default_sashimi_boost_path(data_dir)

        boost_interp, boost_interp_metadata = build_total_boost_interpolator(
            model=subhalo_model,
            table_path=subhalo_boost_table_path,
            fallback_to_unity=subhalo_fallback_to_unity,
            clip_min_boost=subhalo_clip_min_boost,
        )
        print(describe_sashimi_table(boost_interp_metadata))

    # ======================================================================
    # Halo annihilation rate table: ann_rates[z, m]
    # ======================================================================

    ann_rates = np.zeros((len(z_s), len(m_s)), dtype=float)
    boost_used = np.ones_like(ann_rates, dtype=float)

    for i_z, z in enumerate(tqdm(z_s, desc="Halo annihilation rate")):
        c_s = np.asarray(cmz(m_s, z), dtype=float)

        if use_subhalo_boost:
            boost_s = np.asarray(boost_interp(m_s, z), dtype=float)
            # Final safety layer.  The interpolator should already do this.
            boost_s = np.where(np.isfinite(boost_s), boost_s, 1.0)
            boost_s = np.maximum(boost_s, subhalo_clip_min_boost)
        else:
            boost_s = np.ones_like(m_s, dtype=float)

        boost_used[i_z] = boost_s

        for i_m, m in enumerate(m_s):
            host_rate = partial_ann_rate_host(m, c_s[i_m], z)  # [Msun^2 / pc^3]
            ann_rates[i_z, i_m] = float(host_rate) * float(boost_s[i_m])

    # ======================================================================
    # Sum over halo mass functions
    # ======================================================================

    # Conditional Press-Schechter table.
    cond_table = np.zeros((len(zext_s), len(d_s)), dtype=float)
    dndm_cond = np.asarray(hmfdata["ps_cond"], dtype=float)  # [1 / cMpc^3 Msun]

    for i_z, z in enumerate(tqdm(zext_s, desc="Conditional PS")):
        if z > z_max:
            continue
        mass_mask = m_s <= m_high_cutoff
        for i_d, d in enumerate(d_s):
            dndm_zd = dndm_cond[i_z, i_d] * mass_mask
            cond_table[i_z, i_d] = np.trapz(ann_rates[i_z] * dndm_zd, m_s)
            # Unit before conversion: [Msun^2/pc^3 / cMpc^3]

    # Unconditional Press-Schechter table.
    ps_table = np.zeros((len(zext_s),), dtype=float)
    dndm_ps = np.asarray(hmfdata["ps"], dtype=float)  # [1 / cMpc^3 Msun]

    for i_z, z in enumerate(tqdm(zext_s, desc="Unconditional PS")):
        if z > z_max:
            continue
        dndm_z = dndm_ps[i_z] * (m_s <= m_high_cutoff)
        ps_table[i_z] = np.trapz(ann_rates[i_z] * dndm_z, m_s)
        # Unit before conversion: [Msun^2/pc^3 / cMpc^3]

    # Sheth-Tormen table.
    st_table = np.zeros((len(zext_s),), dtype=float)
    dndm_st = np.asarray(hmfdata["st"], dtype=float)  # [1 / cMpc^3 Msun]

    for i_z, z in enumerate(tqdm(zext_s, desc="Unconditional ST")):
        if z > z_max:
            continue
        dndm_z = dndm_st[i_z] * (m_s <= m_high_cutoff)
        st_table[i_z] = np.trapz(ann_rates[i_z] * dndm_z, m_s)
        # Unit before conversion: [Msun^2/pc^3 / cMpc^3]

    # ======================================================================
    # Unit conversion and save
    # ======================================================================

    # Convert [Msun^2/pc^3 / cMpc^3] into [eV^2 / cm^3 / cfcm^3].
    # This follows the original script exactly.
    unit_conversion = (1 * c.M_sun**2 * c.c**4 / (u.pc**3 * u.Mpc**3)).to(
        u.eV**2 / u.cm**3 / u.cm**3
    )
    unit_conversion = float(unit_conversion.value)

    if use_subhalo_boost:
        subhalo_config = describe_model_configuration(
            model=subhalo_model,
            table_path=subhalo_boost_table_path,
            fallback_to_unity=subhalo_fallback_to_unity,
            clip_min_boost=subhalo_clip_min_boost,
        )
        boost_z_grid = np.asarray(boost_interp_metadata["z_grid"], dtype=float)
        boost_M_grid = np.asarray(boost_interp_metadata["M_grid"], dtype=float)
        boost_table = np.asarray(boost_interp_metadata["table"], dtype=float)
        boost_source_file = str(boost_interp_metadata.get("filename", subhalo_boost_table_path))
        boost_min = float(np.nanmin(boost_table))
        boost_max = float(np.nanmax(boost_table))
    else:
        subhalo_config = "none"
        boost_z_grid = np.array([0.0], dtype=float)
        boost_M_grid = np.array([1.0], dtype=float)
        boost_table = np.array([[1.0]], dtype=float)
        boost_source_file = "none"
        boost_min = 1.0
        boost_max = 1.0

    data = {
        "cell_size": hmfdata["cell_size"],
        "r_fixed": hmfdata["r_fixed"],
        "z": zext_s,
        "d": d_s,
        "ps_cond": cond_table * unit_conversion,
        "ps": ps_table * unit_conversion,
        "st": st_table * unit_conversion,
        "hmf_m_min": float(m_s[0]),
        "hmf_m_max": float(m_s[-1]),
        "m_high_cutoff": float(m_high_cutoff) if np.isfinite(m_high_cutoff) else np.inf,
        "subhalo_boost": bool(use_subhalo_boost),
        "subhalo_model": _as_h5_string(subhalo_model if use_subhalo_boost else "none"),
        "subhalo_config": _as_h5_string(subhalo_config),
        "subhalo_boost_source_file": _as_h5_string(boost_source_file),
        "subhalo_boost_z_grid": boost_z_grid,
        "subhalo_boost_M_grid": boost_M_grid,
        "subhalo_boost_table": boost_table,
        "subhalo_boost_min": boost_min,
        "subhalo_boost_max": boost_max,
        "subhalo_fallback_to_unity": bool(subhalo_fallback_to_unity),
        "subhalo_clip_min_boost": float(subhalo_clip_min_boost),
        # Useful diagnostic: the boost values actually sampled on the HMF grid.
        # Shape is (len(hmf z), len(hmf m)).  This is normally much smaller than
        # the SASHIMI production table and helps sanity checks later.
        "subhalo_boost_on_hmf_grid": boost_used,
        "units": _as_h5_string(
            "cell_size: [cMpc]. r_fixed: [cMpc]. z: [1]. d: [1]. "
            "All rates: [eV^2 / cm^3 / cfcm^3]."
        ),
        "shapes": _as_h5_string(
            "ps_cond: (z, d). ps, st: (z,). "
            "subhalo_boost_on_hmf_grid: (hmf_z, hmf_m)."
        ),
    }

    out_path = save_dir / filename
    save_h5_dict(str(out_path), data)
    print(f"Saved: {out_path}")
